fix: modify commit-check workflow to handle single commit pull requests

diff --git a/.github/workflows/Commit Check.yml b/.github/workflows/Commit Check.yml
--- a/.github/workflows/Commit Check.yml
+++ b/.github/workflows/Commit Check.yml
@@ -11,14 +11,21 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout PR
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
 
-    - name: Check PR title
-      run: |
-        pr_title=$(git log --format=%s --no-merges -n 1 ${{ github.event.before }}..${{ github.event.after }})
-        regex_pattern="^(feat|fix|chore|docs|style|refactor|test)(\(.+\))?: .+"
-        if [[ ! $pr_title =~ $regex_pattern ]]; then
-          echo "error: Invalid PR title. Please follow the commit message convention."
-          exit 1
-        fi
+      - name: Get PR Title
+        id: pr_title
+        run: echo "::set-output name=title::$(git show -s --format=%s)"
+
+      - name: Check PR Title Format
+        run: |
+          pr_title="${{ steps.pr_title.outputs.title }}"
+          regex_pattern="^(feat|fix|chore|docs|style|refactor|test)(\(.+\))?: .+"
+          if [[ ! $pr_title =~ $regex_pattern ]]; then
+            echo "error: Invalid PR title. Please follow the commit message convention."
+            exit 1
+          fi
